### ISSUE TITLE
Is working simultaneously ?

### ISSUE THREAD

**Issue by flavienbwk** [kiuz/PPM-Signal-Reader-ARDUINO#4]
Hello,

I'm writing a program on which I need to read 6 ppm outputs.
But strangely, the program only reads 3 out of 6 outputs (the 1, 3 and 5). Strange no ?
They are declared the same way.

Did you notice any problem when reading multiple outputs ?

Thank you for this amazing library!

**Comment by flavbleach** [comment]
I've checked on a previous version of Arduino and it's working.

It seems like the new version (1.8) does not want to make the PPM reader work (correctly).
The 1.0.6 version works like a charm.

**Comment by kiuz** [comment]
thank for you ISSUE, i never used over 3 channel for my experiment, but i think fork on 6 differente channel. But I must test.
 
Try to test separately your 6 input and update me... 
Another try is "use only "PWM pin", in theory it is useless, but you can try because you told me you have used pins 1,3,5.

update me

now i can't te

**Comment by flavbleach** [comment]
Thank you for your answer,

Test with PWM pins failed (version 1.8).
Individually, I tested the 3 problematic pins and it returned 0.
But the 3 others worked !

It seems like the function pulseIn() can't handle more than 3 inputs on version 1.8 whereas it works perfectly on version 1.0.6 !

But what's strange is that among the declared pins (for example 1,2,3,4,5 and 6), the pins that are not working are 2, 4 and 6 ! 1/2 is not working lol. 

So I use the 1.0.6 version of arduino anyway.
Have a great day!

**Comment by kiuz** [comment]
Thanks a lot of your tests!

> But what's strange is that among the declared pins (for example 1,2,3,4,5 and 6), the pins that are not working are 2, 4 and 6 ! 1/2 is not working lol.

it's very strange, I never used over 3 pins because my PPM receiver/sender has only three ppm channel. But I write the library to use every time you want.

> It seems like the function pulseIn() can't handle more than 3 inputs on version 1.8 whereas it works perfectly on version 1.0.6 !

It's very-very strange that pulseIn() can't handle more then 3 input, but if work perfectly on 1.0.6.

I have he suspect the problem may be the file
Arduino.h or WProgram.h imported in .cpp and .h files to include for all the Arduino specific stuff and the AVR stuff...

I think is changed some specifics in 1.8 and some functions, and don't work correctly. 
thanks a lot for you test, i added your information of testing in my README file, and obviously your name for credit.


if you have some other suggestion or test contact me.


kind regards

**Comment by flavbleach** [comment]
A pleasure!

Maybe yes :/

Thank you for the references!
